#ifndef TPMS_H
#define TPMS_H
// заголовок библиотеки систем контроля давления в шинах

#include "..\gdefines.h"

#define TPMS_WHEELS_MAX 34
#define TPMS_WHEEL_INDEX_MIN 0
#define TPMS_WHEEL_INDEX_MAX (TPMS_WHEELS_MAX - 1)

#define TPMS_REASON_PERIODIC 0
#define TPMS_REASON_PRES_UNDER_10 1 // PressurePro: 10%, TPMS: 12,5%
#define TPMS_REASON_PRES_UNDER_20 2 // PressurePro: 20%, TPMS: 25%
#define TPMS_REASON_OVERTEMP 3 // TPMS
#define TPMS_REASON_PRES_FAST_DEC 4 // TPMS
#define TPMS_REASON_PRES_UNDER_50 5 // TPMS
#define TPMS_REASON_NEWAIR_OVERPRES 6 // PressurePro: new air, TPMS: overtemp
#define TPMS_REASON_NEWMAGNET 7 // PressurePro
#define TPMS_REASON_MIN TPMS_REASON_PERIODIC
#define TPMS_REASON_MAX TPMS_REASON_NEWMAGNET

#define TPMS_WHEELTAG_PRES_BYTE 0
#define TPMS_WHEELTAG_TEMP_BYTE 1
#define TPMS_WHEELTAG_TEMP_MIN -128
#define TPMS_WHEELTAG_TEMP_MAX 127
#define TPMS_WHEELTAG_TEMP_MASK 0xFF
#define TPMS_WHEELTAG_TEMP_LSHIFT (TPMS_WHEELTAG_TEMP_BYTE * 8)
#define TPMS_WHEELTAG_FLAGS_BYTE 2
#define TPMS_WHEELTAG_FLAGS_LSHIFT (TPMS_WHEELTAG_FLAGS_BYTE * 8)
#define TPMS_WHEELTAG_FLAGS_ONLINE_BIT 0
#define TPMS_WHEELTAG_FLAGS_ERROR_BIT 1
#define TPMS_WHEELTAG_FLAGS_REASON_BIT 2

#define TPMS_REASON_BITS 3

#define TPMS_PRESSURE_MIN 0
#define TPMS_PRESSURE_MAX 255

#define TPMS_WHEEL_DATA [ \
    .temperature,\
    .pressurePsi,\
    .sensorOnline,\
    .sensorOk,\
    .reason,\
]

#define TPMS_COMTAG_WHEEL_PRES_BYTE 0
#define TPMS_COMTAG_WHEEL_PRES_SIZE 1
#define TPMS_COMTAG_WHEEL_TEMPFLAGS_BYTE (TPMS_COMTAG_WHEEL_PRES_BYTE + TPMS_COMTAG_WHEEL_PRES_SIZE)
#define TPMS_COMTAG_WHEEL_TEMPFLAGS_SIZE 1
#define TPMS_COMTAG_WHEEL_TEMP_BIT 0
#define TPMS_COMTAG_WHEEL_TEMP_BITS 3
#define TPMS_COMTAG_WHEEL_TEMP_MASK 0xFF
#define TPMS_COMTAG_TEMP_MIN -40
#define TPMS_COMTAG_TEMP_MAX 100
#define TPMS_COMTAG_TEMP_STEP ((TPMS_COMTAG_TEMP_MAX - TPMS_COMTAG_TEMP_MIN) / ((1 << TPMS_COMTAG_WHEEL_TEMP_BITS) - 1))
#define TPMS_COMTAG_WHEEL_ONLINE_BIT (TPMS_COMTAG_WHEEL_TEMP_BIT + TPMS_COMTAG_WHEEL_TEMP_BITS)
#define TPMS_COMTAG_WHEEL_ERROR_BIT TPMS_COMTAG_WHEEL_ONLINE_BIT + 1
#define TPMS_COMTAG_WHEEL_REASON_BIT TPMS_COMTAG_WHEEL_ERROR_BIT + 1
#define TPMS_COMTAG_WHEEL_INIT_VALUE ((TPMS_REASON_PERIODIC << TPMS_COMTAG_WHEEL_REASON_BIT) \
                                    + (1 << TPMS_COMTAG_WHEEL_ERROR_BIT) \
                                    + (1 << TPMS_COMTAG_WHEEL_ONLINE_BIT))
#define TPMS_COMTAG_WHEEL_SIZE (TPMS_COMTAG_WHEEL_PRES_SIZE + TPMS_COMTAG_WHEEL_TEMPFLAGS_SIZE)
#define TPMS_COMTAG_WHEELS_SIZE (TPMS_WHEELS_MAX * TPMS_COMTAG_WHEEL_SIZE)
#define TPMS_COMTAG_SEND_FLAG_POS (TAG_TPMS_SIZE - 1)


tpmsWriteCommonTag(const wheels[TPMS_WHEELS_MAX][TPMS_WHEEL_DATA]);
tpmsClearCommonTag();
tpmsWriteWheelTag(wheelIdx, const wheel[TPMS_WHEEL_DATA]);
tpmsInitWheels(wheels[TPMS_WHEELS_MAX][TPMS_WHEEL_DATA]);

#endif
