#ifndef BLUETOOTH_H
#define BLUETOOTH_H

#define BLUETOOTH_MAC_SIZE 6
#define BLUETOOTH_RSSI_MASK 0xFFFFFF00

#define BLUETOOTH_ADV_DATA_SIZE_MAX 32
#define BLUETOOTH_ADSTRUCT_TYPE_SIZE 1
#define BLUETOOTH_ADSTRUCT_SIZE_MIN (BLUETOOTH_ADSTRUCT_TYPE_SIZE + 1)
#define BLUETOOTH_ADSTRUCT_DATA_SIZE_MAX (BLUETOOTH_ADV_DATA_SIZE_MAX - BLUETOOTH_ADSTRUCT_SIZE_MIN)
#define BLUETOOTH_ADSTRUCT [\
    .type,\
    .dataSize,\
    .data{BLUETOOTH_ADSTRUCT_DATA_SIZE_MAX}\
]

// типы данных AD структур
#define BLUETOOTH_ADTYPE_SHORT_LOCAL_NAME 0x08
#define BLUETOOTH_ADTYPE_COMPL_LOCAL_NAME 0x09
#define BLUETOOTH_ADTYPE_SRVCDATA_UUID16BIT 0x16

// ADTYPE_SRVCDATA_UUID16BIT
#define BLUETOOTH_ADTYPE_SRVCDATA_UUID16BIT_SIZE 2

bluetoothGetRssi(const msg[BTMSG]);
bluetoothGetAdStruct(const msg[BTMSG], pos, adStruct[BLUETOOTH_ADSTRUCT]);
bluetoothGetLocalName(const adStruct[BLUETOOTH_ADSTRUCT], nameMaxSize, name{}, &nameSize);

#endif