#ifndef BLUETOOTH_H
#define BLUETOOTH_H

#define BLUETOOTH_MAC_SIZE 6
#define BLUETOOTH_RSSI_MASK 0xFFFFFF00

#define BLUETOOTH_ADV_DATA_SIZE_MAX 32

// AD структура
#define BLUETOOTH_ADSTRUCT_LEN_POS 0
#define BLUETOOTH_ADSTRUCT_LEN_SIZE 1
#define BLUETOOTH_ADSTRUCT_LEN_MIN 2
#define BLUETOOTH_ADSTRUCT_TYPE_POS (BLUETOOTH_ADSTRUCT_LEN_POS + BLUETOOTH_ADSTRUCT_LEN_SIZE)
#define BLUETOOTH_ADSTRUCT_TYPE_SIZE 1
#define BLUETOOTH_ADSTRUCT_PAYLOAD_POS (BLUETOOTH_ADSTRUCT_TYPE_POS + BLUETOOTH_ADSTRUCT_TYPE_SIZE)
#define BLUETOOTH_ADSTRUCT_DATA_SIZE_MIN 1
#define BLUETOOTH_ADSTRUCT_SIZE_MIN (BLUETOOTH_ADSTRUCT_LEN_MIN + BLUETOOTH_ADSTRUCT_LEN_SIZE)
#define BLUETOOTH_ADSTRUCT_DATA_SIZE_MAX (BLUETOOTH_ADV_DATA_SIZE_MAX - BLUETOOTH_ADSTRUCT_SIZE_MIN)
#define BLUETOOTH_ADSTRUCT [\
    .type,\
    .dataSize,\
    .data{BLUETOOTH_ADSTRUCT_DATA_SIZE_MAX}\
]

// типы данных AD структур
#define BLUETOOTH_ADTYPE_SHORT_LOCAL_NAME 0x08
#define BLUETOOTH_ADTYPE_COMPL_LOCAL_NAME 0x09
#define BLUETOOTH_ADTYPE_SRVCDATA_UUID16BIT 0x16
#define BLUETOOTH_ADTYPE_MFRSPECDATA 0xFF

// ADTYPE_SRVCDATA_UUID16BIT
#define BLUETOOTH_ADTYPE_SRVCDATA_UUID16BIT_UUID_POS 0
#define BLUETOOTH_ADTYPE_SRVCDATA_UUID16BIT_SIZE 2

// ADTYPE_MFRSPECDATA
#define BLUETOOTH_MFRSPECDATA_COMP_ID_POS 0
#define BLUETOOTH_MFRSPECDATA_COMP_ID_SIZE 2

bluetoothGetRssi(const msg[BTMSG]);
bluetoothGetAdStruct(const msg[BTMSG], pos, adStruct[BLUETOOTH_ADSTRUCT]);
bluetoothGetLocalName(const msg[BTMSG], nameMaxSize, name{}, &nameSize = 0);
bluetoothGetComplName(const msg[BTMSG], nameMaxSize, name{}, &nameSize = 0);
bluetoothGetShortlName(const msg[BTMSG], nameMaxSize, name{}, &nameSize = 0);
bluetoothGetAdStructType(const msg[BTMSG], type, adStruct[BLUETOOTH_ADSTRUCT]);

#endif
