#ifndef USERARRAY_H
#define USERARRAY_H
// Заголовок библиотеки массива пользователя

#include "..\gdefines.h"

#define USERARRAY_TYPE_POS 0

#define USERARRAY_PASCOUNT_TYPE 0x0A
#define USERARRAY_PASCOUNT_TYPE_SIZE 1
#define USERARRAY_PASCOUNT_SENSOR_ADDR_POS 0
#define USERARRAY_PASCOUNT_SENSOR_ADDR_SIZE 3
#define USERARRAY_PASCOUNT_SENSOR_ADDR_MIN 0x00
#define USERARRAY_PASCOUNT_SENSOR_ADDR_MAX 0xFFFFFF
#define USERARRAY_PASCOUNT_SENSOR_STATE_POS (USERARRAY_PASCOUNT_SENSOR_ADDR_POS + USERARRAY_PASCOUNT_SENSOR_ADDR_SIZE)
#define USERARRAY_PASCOUNT_SENSOR_STATE_SIZE 1
#define USERARRAY_PASCOUNT_SENSOR_DATA_SIZE 2
#define USERARRAY_PASCOUNT_SENSOR_IN_POS (USERARRAY_PASCOUNT_SENSOR_STATE_POS + USERARRAY_PASCOUNT_SENSOR_STATE_SIZE)
#define USERARRAY_PASCOUNT_SENSOR_IN_SIZE USERARRAY_PASCOUNT_SENSOR_DATA_SIZE
#define USERARRAY_PASCOUNT_SENSOR_OUT_POS (USERARRAY_PASCOUNT_SENSOR_IN_POS + USERARRAY_PASCOUNT_SENSOR_IN_SIZE)
#define USERARRAY_PASCOUNT_SENSOR_OUT_SIZE USERARRAY_PASCOUNT_SENSOR_DATA_SIZE
#define USERARRAY_PASCOUNT_SENSOR_DATA_MIN 0
#define USERARRAY_PASCOUNT_SENSOR_DATA_MAX 65535
#define USERARRAY_PASCOUNT_SENSOR_SIZE (USERARRAY_PASCOUNT_SENSOR_OUT_POS + USERARRAY_PASCOUNT_SENSOR_OUT_SIZE)
#define USERARRAY_PASCOUNT_SENSORS_QTY_MAX 8
#define USERARRAY_PASCOUNT_SIZE_MAX (USERARRAY_PASCOUNT_TYPE_SIZE + (USERARRAY_PASCOUNT_SENSORS_QTY_MAX * USERARRAY_PASCOUNT_SENSOR_SIZE))
#define USERARRAY_PASCOUNT_DATA_POS_MIN USERARRAY_PASCOUNT_TYPE_SIZE
#define USERARRAY_PASCOUNT_DATA_POS_MAX (USERARRAY_PASCOUNT_SIZE_MAX - USERARRAY_PASCOUNT_SENSOR_SIZE)

#define USERARRAY_PASCOUNT_SENSOR_DATA [\
    .addr,\
    .state,\
    .incoming,\
    .outgoing,\
]

#define USERARRAY_USTRUCT_TYPE 0x7F
#define USERARRAY_USTRUCT_TYPE_SIZE 1
#define USERARRAY_USTRUCT_DESCR_SIZE 1
#define USERARRAY_USTRUCT_DESCR_SYMBOLS_MAX 127
#define USERARRAY_USTRUCT_DESCR_NUMBERS_MAX 8

#define USERARRAY_MAX_SIZE TAG_USER_ARRAY_MAX_SIZE

#define USERARRAY_FILE_TYPE 0x80
#define USERARRAY_FILE_TYPE_LEN 1
#define USERARRAY_FILE_UID_POS (USERARRAY_TYPE_POS + USERARRAY_FILE_TYPE_LEN)
#define USERARRAY_FILE_UID_LEN 4
#define USERARRAY_FILE_NCHUNK_POS (USERARRAY_FILE_UID_POS + USERARRAY_FILE_UID_LEN)
#define USERARRAY_FILE_NCHUNK_LEN 3
#define USERARRAY_FILE_SIZE_POS (USERARRAY_FILE_NCHUNK_POS + USERARRAY_FILE_NCHUNK_LEN)
#define USERARRAY_FILE_SIZE_LEN 1
#define USERARRAY_FILE_HEADER_LEN (USERARRAY_FILE_TYPE_LEN + USERARRAY_FILE_UID_LEN + USERARRAY_FILE_NCHUNK_LEN + USERARRAY_FILE_SIZE_LEN)
#define USERARRAY_FILE_DATA_POS (USERARRAY_FILE_SIZE_POS + USERARRAY_FILE_SIZE_LEN)
#define USERARRAY_FILE_CRC_LEN 1
#define USERARRAY_FILE_FRAME_LEN_MIN (USERARRAY_FILE_HEADER_LEN + USERARRAY_FILE_CRC_LEN)
#define USERARRAY_FILE_CHUNK_LEN_MAX (USERARRAY_MAX_SIZE - USERARRAY_FILE_FRAME_LEN_MIN)

ustructMakeDescriptor(isNumbers, amount, size);
ustructMakeDescriptorNum(amount, size);
ustructMakeDescriptorStr(strSize);
ustructInsertEmpty(userArray{}, userArrayMaxSize, &pos, emptyCount);
sendFileInUserArray(const fileName{}, &lastFileId);
userArrayAddPasCounting(userArray{}, userArrayMaxSize, const sensor[USERARRAY_PASCOUNT_SENSOR_DATA], &pos);

#endif // USERARRAY_H
