#ifndef USERARRAY_H
#define USERARRAY_H
// Заголовок библиотеки массива пользователя

#include "..\gdefines.h"

#define USERARRAY_TYPE_POS 0

#define USERARRAY_USTRUCT_TYPE 0x7F
#define USERARRAY_USTRUCT_TYPE_SIZE 1
#define USERARRAY_USTRUCT_DESCR_SIZE 1
#define USERARRAY_USTRUCT_DESCR_SYMBOLS_MAX 127
#define USERARRAY_USTRUCT_DESCR_NUMBERS_MAX 8

#define USERARRAY_MAX_SIZE TAG_USER_ARRAY_MAX_SIZE

#define USERARRAY_FILE_TYPE 0x80
#define USERARRAY_FILE_TYPE_LEN 1
#define USERARRAY_FILE_UID_POS (USERARRAY_TYPE_POS + USERARRAY_FILE_TYPE_LEN)
#define USERARRAY_FILE_UID_LEN 4
#define USERARRAY_FILE_NCHUNK_POS (USERARRAY_FILE_UID_POS + USERARRAY_FILE_UID_LEN)
#define USERARRAY_FILE_NCHUNK_LEN 3
#define USERARRAY_FILE_SIZE_POS (USERARRAY_FILE_NCHUNK_POS + USERARRAY_FILE_NCHUNK_LEN)
#define USERARRAY_FILE_SIZE_LEN 1
#define USERARRAY_FILE_HEADER_LEN (USERARRAY_FILE_TYPE_LEN + USERARRAY_FILE_UID_LEN + USERARRAY_FILE_NCHUNK_LEN + USERARRAY_FILE_SIZE_LEN)
#define USERARRAY_FILE_DATA_POS (USERARRAY_FILE_SIZE_POS + USERARRAY_FILE_SIZE_LEN)
#define USERARRAY_FILE_CRC_LEN 1
#define USERARRAY_FILE_FRAME_LEN_MIN (USERARRAY_FILE_HEADER_LEN + USERARRAY_FILE_CRC_LEN)
#define USERARRAY_FILE_CHUNK_LEN_MAX (USERARRAY_MAX_SIZE - USERARRAY_FILE_FRAME_LEN_MIN)

ustructMakeDescriptor(isNumbers, amount, size);
ustructMakeDescriptorNum(amount, size);
ustructMakeDescriptorStr(strSize);
ustructInsertEmpty(userArray{}, userArrayMaxSize, &pos, emptyCount);
sendFileInUserArray(const fileName{}, &lastFileId);

#endif // USERARRAY_H