#ifndef JFIF_H
#define JFIF_H
// заголовок библиотеки работы с JFIF изображениями

#include "..\jpeg.h"

#define JFIF_SEGMENT_ID JPEG_SEGMENT_APP0_ID
stock const JFIF_SEGMENT_MARKER{} = {JPEG_SEGMENT_MARKER_PREFIX, JFIF_SEGMENT_ID};
#define JFIF_SEGMENT_MARKER_SIZE JPEG_SEGMENT_MARKER_SIZE
#define JFIF_LEN_POS JPEG_SEGMENT_APP_LEN_POS
#define JFIF_LEN_SIZE JPEG_SEGMENT_APP_LEN_SIZE
#define JFIF_ASCII_POS (JFIF_LEN_POS + JFIF_LEN_SIZE)
#define JFIF_ASCII "JFIF\0"
#define JFIF_ASCII_SIZE 5
#define JFIF_VER_MAJOR_POS (JFIF_ASCII_POS + JFIF_ASCII_SIZE)
#define JFIF_VER_MAJOR_SIZE 1
#define JFIF_VER_MINOR_POS (JFIF_VER_MAJOR_POS + JFIF_VER_MAJOR_SIZE)
#define JFIF_VER_MINOR_SIZE 1
#define JFIF_DENSITY_UNITS_POS (JFIF_VER_MINOR_POS + JFIF_VER_MINOR_SIZE)
#define JFIF_DENSITY_UNITS_SIZE 1
#define JFIF_DENSITY_X_POS (JFIF_DENSITY_UNITS_POS + JFIF_DENSITY_UNITS_SIZE)
#define JFIF_DENSITY_X_SIZE 2
#define JFIF_DENSITY_Y_POS (JFIF_DENSITY_X_POS + JFIF_DENSITY_X_SIZE)
#define JFIF_DENSITY_Y_SIZE 2
#define JFIF_THUMBNAIL_X_POS (JFIF_DENSITY_Y_POS + JFIF_DENSITY_Y_SIZE)
#define JFIF_THUMBNAIL_X_SIZE 1
#define JFIF_THUMBNAIL_Y_POS (JFIF_DENSITY_X_POS + JFIF_DENSITY_X_SIZE)
#define JFIF_THUMBNAIL_Y_SIZE 1
#define JFIF_THUMBNAIL_DATA_POS (JFIF_THUMBNAIL_Y_POS + JFIF_THUMBNAIL_Y_SIZE)
#define JFIF_THUMBNAIL_DATA_SIZE_MIN 0
#define JFIF_SIZE_MIN (JFIF_SEGMENT_MARKER_SIZE + JFIF_LEN_SIZE + JFIF_ASCII_SIZE + JFIF_VER_MAJOR_SIZE + JFIF_VER_MINOR_SIZE + JFIF_DENSITY_UNITS_SIZE + \
                        JFIF_DENSITY_X_SIZE + JFIF_DENSITY_Y_SIZE + JFIF_THUMBNAIL_X_SIZE + JFIF_THUMBNAIL_Y_SIZE + JFIF_THUMBNAIL_DATA_SIZE_MIN)
#define JFIF_LEN_MIN (JFIF_SIZE_MIN - JFIF_SEGMENT_MARKER_SIZE)
#define JFIF_FILE_POS (JPEG_SEGMENT_SOI_POS + JPEG_SEGMENT_SOI_SIZE)

// расширение (JFXX, если используется, то должен идти сразу за JFIF)
#define JFXX_SEGMENT_ID JPEG_SEGMENT_APP0_ID
stock const JFXX_SEGMENT_MARKER{} = {JPEG_SEGMENT_MARKER_PREFIX, JFXX_SEGMENT_ID};
#define JFXX_SEGMENT_MARKER_SIZE JPEG_SEGMENT_MARKER_SIZE
#define JFXX_LEN_POS JPEG_SEGMENT_APP_LEN_POS
#define JFXX_LEN_SIZE JPEG_SEGMENT_APP_LEN_SIZE
#define JFXX_ASCII_POS (JFXX_LEN_POS + JFXX_LEN_SIZE)
#define JFXX_ASCII "JFXX\0"
#define JFXX_ASCII_SIZE 5
#define JFXX_THUMBNAIL_FORMAT_POS (JFXX_ASCII_POS + JFXX_ASCII_SIZE)
#define JFXX_THUMBNAIL_FORMAT_SIZE 1
#define JFXX_THUMBNAIL_DATA_POS (JFXX_THUMBNAIL_FORMAT_POS + JFXX_THUMBNAIL_FORMAT_SIZE)
#define JFXX_THUMBNAIL_DATA_SIZE_MIN 0 // на самом деле больше, но для проверок пока хватит
#define JFXX_SIZE_MIN (JFXX_SEGMENT_MARKER_SIZE + JFXX_LEN_SIZE + JFXX_ASCII_SIZE + JFXX_THUMBNAIL_FORMAT_SIZE + JFXX_THUMBNAIL_DATA_SIZE_MIN)

#endif
